// <auto-generated />
using System;
using Arbitrage.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arbitrage.Infrastructure.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260922003301_PublicMarketCatalog")]
    partial class PublicMarketCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Arbitrage.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Arbitrage.Domain.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("WorkspaceId", "OccurredAt");

                    b.ToTable("AuditRecords");
                });

            modelBuilder.Entity("Arbitrage.Domain.LocalProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DefaultWorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slot")
                        .IsUnique();

                    b.HasIndex("UserId", "DefaultWorkspaceId");

                    b.ToTable("LocalProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_Profile_Slot", "Slot = 1");
                        });
                });

            modelBuilder.Entity("Arbitrage.Domain.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workspaces", t =>
                        {
                            t.HasCheckConstraint("CK_Workspace_Name", "length(trim(DisplayName)) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("Arbitrage.Domain.WorkspaceMembership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "WorkspaceId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Memberships", t =>
                        {
                            t.HasCheckConstraint("CK_Membership_Role", "Role = 0");
                        });
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.DiscoveryRunEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentScope")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int>("Malformed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Observed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RetryAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Exchange", "StartedAt");

                    b.HasIndex("Exchange", "State");

                    b.ToTable("DiscoveryRuns");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.MarketCatalogEntry", b =>
                {
                    b.Property<string>("Exchange")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CloseAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpectedResolutionAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstRetrievedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIncomplete")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LastSeenRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeStatus")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OpenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutcomesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryTag")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RetrievedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rules")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceUpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Exchange", "NativeId");

                    b.HasIndex("RetrievedAt");

                    b.HasIndex("Exchange", "PrimaryTag", "NativeId");

                    b.HasIndex("Exchange", "Status", "Title", "NativeId");

                    b.ToTable("CatalogMarkets");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.MarketCatalogTag", b =>
                {
                    b.Property<string>("Exchange")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Exchange", "NativeId", "Tag");

                    b.HasIndex("Tag");

                    b.ToTable("CatalogTags");
                });

            modelBuilder.Entity("Arbitrage.Domain.AuditRecord", b =>
                {
                    b.HasOne("Arbitrage.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arbitrage.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Domain.LocalProfile", b =>
                {
                    b.HasOne("Arbitrage.Domain.WorkspaceMembership", null)
                        .WithMany()
                        .HasForeignKey("UserId", "DefaultWorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Domain.WorkspaceMembership", b =>
                {
                    b.HasOne("Arbitrage.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arbitrage.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.MarketCatalogTag", b =>
                {
                    b.HasOne("Arbitrage.Infrastructure.MarketCatalogEntry", null)
                        .WithMany()
                        .HasForeignKey("Exchange", "NativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
