// <auto-generated />
using System;
using Arbitrage.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arbitrage.Infrastructure.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260923154728_PaperRiskPolicy")]
    partial class PaperRiskPolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Arbitrage.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Arbitrage.Domain.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("WorkspaceId", "OccurredAt");

                    b.ToTable("AuditRecords");
                });

            modelBuilder.Entity("Arbitrage.Domain.LocalProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DefaultWorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slot")
                        .IsUnique();

                    b.HasIndex("UserId", "DefaultWorkspaceId");

                    b.ToTable("LocalProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_Profile_Slot", "Slot = 1");
                        });
                });

            modelBuilder.Entity("Arbitrage.Domain.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workspaces", t =>
                        {
                            t.HasCheckConstraint("CK_Workspace_Name", "length(trim(DisplayName)) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("Arbitrage.Domain.WorkspaceMembership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "WorkspaceId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Memberships", t =>
                        {
                            t.HasCheckConstraint("CK_Membership_Role", "Role = 0");
                        });
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.DiscoveryRunEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentScope")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int>("Malformed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Observed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RetryAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Exchange", "StartedAt");

                    b.HasIndex("Exchange", "State");

                    b.ToTable("DiscoveryRuns");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.FeeProfileEntry", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Profile")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Revision")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkspaceId");

                    b.ToTable("FeeProfiles");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.FeeScheduleEntry", b =>
                {
                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RetrievedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Exchange", "MarketId");

                    b.ToTable("FeeSchedules");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.MarketCatalogEntry", b =>
                {
                    b.Property<string>("Exchange")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CloseAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpectedResolutionAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstRetrievedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIncomplete")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LastSeenRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeStatus")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OpenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutcomesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipMetadataBaseFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipMetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RetrievedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rules")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceUpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Exchange", "NativeId");

                    b.HasIndex("RetrievedAt");

                    b.HasIndex("Exchange", "PrimaryTag", "NativeId");

                    b.HasIndex("Exchange", "Status", "Title", "NativeId");

                    b.ToTable("CatalogMarkets");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.MarketCatalogTag", b =>
                {
                    b.Property<string>("Exchange")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Exchange", "NativeId", "Tag");

                    b.HasIndex("Tag");

                    b.ToTable("CatalogTags");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.MarketRelationshipEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CollectivelyExhaustive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastValidatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MutuallyExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewReason")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReviewedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceExchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetExchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "State");

                    b.HasIndex("WorkspaceId", "Type");

                    b.HasIndex("WorkspaceId", "TargetExchange", "TargetId");

                    b.HasIndex("WorkspaceId", "SourceExchange", "SourceId", "TargetExchange", "TargetId")
                        .IsUnique();

                    b.ToTable("MarketRelationships", (string)null);
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.MonitoringAlertEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TriggeredAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "TriggeredAt", "Id");

                    b.ToTable("MonitoringAlerts");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.MonitoringProfileEntry", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Revision")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkspaceId");

                    b.ToTable("MonitoringProfiles");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperBalanceEntry", b =>
                {
                    b.Property<Guid>("GenerationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvailableCash")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialCash")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReservedCash")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("GenerationId", "Exchange", "Currency");

                    b.ToTable("PaperBalanceEntry");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperExecutionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpportunityKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RiskPolicyRevision")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RiskPolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RiskProofJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SettledAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettlementJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettlementMarketsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("GenerationId", "State");

                    b.HasIndex("WorkspaceId", "CreatedAt");

                    b.HasIndex("WorkspaceId", "RequestId")
                        .IsUnique();

                    b.ToTable("PaperExecutionEntry");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperFillEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FillJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LegId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegId");

                    b.ToTable("PaperFillEntry");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperGenerationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClosedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Integrity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("WorkspaceId")
                        .IsUnique()
                        .HasFilter("\"ClosedAt\" IS NULL");

                    b.ToTable("PaperGenerationEntry");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvailableDelta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReservedDelta")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("PaperLedgerEntry");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperLegEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fees")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Notional")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.ToTable("PaperLegEntry");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperPositionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageEntry")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostBasis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fees")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OpenedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RealizedPnl")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SettledAt")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SettlementPayout")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SettlementResolutionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SettlementResolutionId");

                    b.HasIndex("GenerationId", "Status");

                    b.HasIndex("GenerationId", "Exchange", "MarketId", "InstrumentId", "Outcome")
                        .IsUnique();

                    b.ToTable("PaperPositionEntry");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperResolutionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProofFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("WorkspaceId", "RequestId")
                        .IsUnique();

                    b.HasIndex("GenerationId", "Exchange", "MarketId")
                        .IsUnique();

                    b.ToTable("PaperResolutionEntry");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperResolutionOutcomeEntry", b =>
                {
                    b.Property<Guid>("ResolutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PayoutPerShare")
                        .HasColumnType("TEXT");

                    b.HasKey("ResolutionId", "InstrumentId");

                    b.ToTable("PaperResolutionOutcomeEntry");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperRiskProfileEntry", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkspaceId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("PaperRiskProfiles", (string)null);
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperTransactionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolutionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("GenerationId");

                    b.HasIndex("ResolutionId")
                        .IsUnique();

                    b.ToTable("PaperTransactionEntry");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.RelationshipEvidenceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Blocking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Contradiction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RelationshipId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipId");

                    b.ToTable("RelationshipEvidence", (string)null);
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.RelationshipJobEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Comparisons")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notice")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sources")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Written")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "StartedAt");

                    b.ToTable("RelationshipJobs");
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.RelationshipOutcomeMappingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelationshipId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceOutcomeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetOutcomeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipId");

                    b.ToTable("RelationshipOutcomeMappings", (string)null);
                });

            modelBuilder.Entity("Arbitrage.Domain.AuditRecord", b =>
                {
                    b.HasOne("Arbitrage.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arbitrage.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Domain.LocalProfile", b =>
                {
                    b.HasOne("Arbitrage.Domain.WorkspaceMembership", null)
                        .WithMany()
                        .HasForeignKey("UserId", "DefaultWorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Domain.WorkspaceMembership", b =>
                {
                    b.HasOne("Arbitrage.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arbitrage.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.FeeProfileEntry", b =>
                {
                    b.HasOne("Arbitrage.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.FeeScheduleEntry", b =>
                {
                    b.HasOne("Arbitrage.Infrastructure.MarketCatalogEntry", null)
                        .WithMany()
                        .HasForeignKey("Exchange", "MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.MarketCatalogTag", b =>
                {
                    b.HasOne("Arbitrage.Infrastructure.MarketCatalogEntry", null)
                        .WithMany()
                        .HasForeignKey("Exchange", "NativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.MarketRelationshipEntry", b =>
                {
                    b.HasOne("Arbitrage.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.MonitoringAlertEntry", b =>
                {
                    b.HasOne("Arbitrage.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.MonitoringProfileEntry", b =>
                {
                    b.HasOne("Arbitrage.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperBalanceEntry", b =>
                {
                    b.HasOne("Arbitrage.Infrastructure.PaperGenerationEntry", null)
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperExecutionEntry", b =>
                {
                    b.HasOne("Arbitrage.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arbitrage.Infrastructure.PaperGenerationEntry", null)
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperFillEntry", b =>
                {
                    b.HasOne("Arbitrage.Infrastructure.PaperLegEntry", null)
                        .WithMany()
                        .HasForeignKey("LegId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperGenerationEntry", b =>
                {
                    b.HasOne("Arbitrage.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arbitrage.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperLedgerEntry", b =>
                {
                    b.HasOne("Arbitrage.Infrastructure.PaperTransactionEntry", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperLegEntry", b =>
                {
                    b.HasOne("Arbitrage.Infrastructure.PaperExecutionEntry", null)
                        .WithMany()
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperPositionEntry", b =>
                {
                    b.HasOne("Arbitrage.Infrastructure.PaperGenerationEntry", null)
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arbitrage.Infrastructure.PaperResolutionEntry", null)
                        .WithMany()
                        .HasForeignKey("SettlementResolutionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperResolutionEntry", b =>
                {
                    b.HasOne("Arbitrage.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arbitrage.Infrastructure.PaperGenerationEntry", null)
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arbitrage.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperResolutionOutcomeEntry", b =>
                {
                    b.HasOne("Arbitrage.Infrastructure.PaperResolutionEntry", null)
                        .WithMany()
                        .HasForeignKey("ResolutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperRiskProfileEntry", b =>
                {
                    b.HasOne("Arbitrage.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arbitrage.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Arbitrage.Execution.PaperRiskLimits", "Limits", b1 =>
                        {
                            b1.Property<Guid>("PaperRiskProfileEntryWorkspaceId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("MaximumInstrumentCostBasisFraction")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("MaximumMarketCostBasisFraction")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("MaximumOpenCostBasisFraction")
                                .HasColumnType("TEXT");

                            b1.Property<int>("MaximumOpenExecutions")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaximumOpenExecutionsPerRelationship")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaximumOpenPositions")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("MaximumRequestedQuantity")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("MaximumSingleExecutionDebitFraction")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("MinimumCashReserveFraction")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("MinimumFeeAdjustedEdgePerShare")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("MinimumFeeAdjustedProfit")
                                .HasColumnType("TEXT");

                            b1.HasKey("PaperRiskProfileEntryWorkspaceId");

                            b1.ToTable("PaperRiskProfiles");

                            b1.WithOwner()
                                .HasForeignKey("PaperRiskProfileEntryWorkspaceId");
                        });

                    b.Navigation("Limits")
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.PaperTransactionEntry", b =>
                {
                    b.HasOne("Arbitrage.Infrastructure.PaperExecutionEntry", null)
                        .WithMany()
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Arbitrage.Infrastructure.PaperGenerationEntry", null)
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arbitrage.Infrastructure.PaperResolutionEntry", null)
                        .WithMany()
                        .HasForeignKey("ResolutionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.RelationshipEvidenceEntry", b =>
                {
                    b.HasOne("Arbitrage.Infrastructure.MarketRelationshipEntry", null)
                        .WithMany("Evidence")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.RelationshipJobEntry", b =>
                {
                    b.HasOne("Arbitrage.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.RelationshipOutcomeMappingEntry", b =>
                {
                    b.HasOne("Arbitrage.Infrastructure.MarketRelationshipEntry", null)
                        .WithMany("Mappings")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arbitrage.Infrastructure.MarketRelationshipEntry", b =>
                {
                    b.Navigation("Evidence");

                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
